### ISSUE TITLE
Meshing the entire domain

### ISSUE THREAD

**Issue by qnzhou** [dengwirda/jigsaw#10]
Hi Darren,

In 2D setting, it seems jigsaw only meshes the regions that is considered "inside."  Is there a way of meshing the entire domain?  For example, I got the following results by using a number of concentric circles as constraints:

![image](https://user-images.githubusercontent.com/3606672/49911711-5cde8e80-fec2-11e8-82ba-c2e361926778.png)

However, I need to mesh the entire domain (e.g. the convex hull in this case).  Similar to what Shewchuk's triangle outputs:

![image](https://user-images.githubusercontent.com/3606672/49912286-adef8200-fec4-11e8-8d2c-1e23178d5c48.png)

As illustrated here, Shewchuk's triangle may produce undesirable cluster of tiny triangles in a few places.  Jigsaw seems to provide higher quality triangulation, but is there a way of meshing the entire domain?

Also, possibly related this, when meshing complex domains, jigsaw sometimes output mesh with tiny holes:

![image](https://user-images.githubusercontent.com/3606672/49911990-76cca100-fec3-11e8-8a12-46a1d0e7bac4.png)

Any clue on why is that?

best,
James

**Comment by dengwirda** [comment]
@qnzhou Yes - I need to do a little work here to allow for the proper specification of 'internal' boundaries. 

Currently `JIGSAW` treats all constraints as if they're part of a bounding contour (defining enclosed areas in 2D or volumes in 3D). I've already partially implemented a system to support both 'internal' and 'external' boundary definitions, but still need to complete a few things before I release this publicly - I'll let you know when it's ready.

**Comment by qnzhou** [comment]
Thanks Darren!  Do you think the tiny holes in the last example is caused by inaccurate inside/outside determination?

**Comment by dengwirda** [comment]
@qnzhou I've added new functionality to `JIGSAW-0.9.8` that should support these kind of geometries. The "squares" example included below shows how to set things up -- using the new `BOUND` array, it's possible to specify which constraints define the boundary of the enclosed domain, and which are to be included as "interior" constraints. 

In this case, the edges of the outer square define the enclosing boundary, and the inner square is an internal constraint.

The 1st column in the `BOUND` array is the `ID` tag assigned to the cells generated inside the enclosed region. The 2nd column is the index of the constraint (in this case the index of the first four `EDGE2` elements that make up the outer square). The 3rd column indicates what kind of constraint is being indexed -- a set of constants are defined in `../inc/jigsaw_const.h`. `EDGE2` elements `== +20`.

When comparing with Shewchuk's `Triangle` code, keep in mind that `JIGSAW` and `Triangle` operate somewhat differently -- `Triangle` is a "constrained" Delaunay algorithm, while `JIGSAW` is a "restricted" Delaunay approach. In brief, this means that `Triangle` will be forced to create a triangle from each boundary edge you specify, while `JIGSAW` will attempt to "resample" the geometry at the mesh size you've specified.

```
# squares.msh geometry file
# two concentric squares, with edges of the inner square imposed
# as "internal" constraints
MSHID=2
NDIMS=2
POINT=8
0;0;0
4;0;0
4;4;0
0;4;0
1;1;0
3;1;0
3;3;0
1;3;0
EDGE2=8
0;1;0
1;2;0
2;3;0
3;0;0
4;5;0
5;6;0
6;7;0
7;4;0
BOUND=4
0;0;20
0;1;20
0;2;20
0;3;20
```

**Comment by qnzhou** [comment]
Thanks @dengwirda !  I am calling jigsaw with the following code:

```
    jigsaw_alloc_bound(&input_mesh._bound, 4);
    input_mesh._bound._data[0]._itag = 0;
    input_mesh._bound._data[0]._indx = 0;
    input_mesh._bound._data[0]._kind = JIGSAW_EDGE2_TAG;
    input_mesh._bound._data[0]._itag = 0;
    input_mesh._bound._data[0]._indx = 1;
    input_mesh._bound._data[0]._kind = JIGSAW_EDGE2_TAG;
    input_mesh._bound._data[0]._itag = 0;
    input_mesh._bound._data[0]._indx = 2;
    input_mesh._bound._data[0]._kind = JIGSAW_EDGE2_TAG;
    input_mesh._bound._data[0]._itag = 0;
    input_mesh._bound._data[0]._indx = 3;
    input_mesh._bound._data[0]._kind = JIGSAW_EDGE2_TAG;
```

However, I got the same output for the "target" example.  Do I need set anything else?

**Comment by dengwirda** [comment]
Ah - right! Somehow I didn't quite get this hooked up correctly in the `API` layer. It should now be working... I've also added a related `BOUND` unit test in `../uni/test_4.c`.

Let me know how you go with this @qnzhou . Your code above looks basically right, though the index into `_bound._data[]` seems always to be zero - maybe just a typo.

**Comment by qnzhou** [comment]
It seems to work.  I thought `_indx` field is the index into `_edge2` data, is it correct?  It is not clear to me what does the `_itag` field do. 

![image](https://user-images.githubusercontent.com/3606672/51445457-fbc48a80-1cb9-11e9-938e-099a180b10d2.png)

Another question that I want to confirm with you is that with restricted Delaunay approach it is possible that the input segment constraints are not preserved as show in the figure above where we do not get a perfect square in the output.

Also somewhat unrelated to this issue, it seems turning on `_mesh_top1` sometimes cause the algorithm to not terminate and exhaust all available memory.  Is it a known issue?

**Comment by dengwirda** [comment]
@qnzhou Oh great - glad it's working. 

Yes `indx` is the cell that's being indexed. Since `kind == JIGSAW_EDGE2_TAG` it's an index into the edge set. The `itag` field can be used to give each enclosed area defined in `BOUND` it's own `ID`. These `ID`'s are assigned to the triangles generated, so the final mesh can consist of multiple "parts".

There are a few options available that control the behaviour of the triangulation algorithm. With the "restricted" approach, the boundaries are re-sampled at the desired mesh size. If the mesh size is larger than the "feature" size of the geometry (as in this case) some level of approximation needs to be introduced. In your example, it's not possible to exactly represent the geometry without introducing cells that are smaller than the target mesh size, so a kind of "best-fit" approximation to the geometry is employed.

It's possible to enforce additional levels of conformance: setting `.geom_feat = true` tries to represent any sharp corners in the geometry exactly, while `.mesh_top1 = true` tries to refine the 1-dimensional cells in the mesh (the edges) until the topology of the geometry is matched. In your example, I'd expect these settings to refine at the circle-square interface until the geometry is fully recovered.

When the feature-detection + topology-recovery settings are active, it's important the geometry is not "ill-posed" in any way (no self-intersections, duplicate edges, etc) or non-termination may occur. If you're seeing non-termination, I'd expect there's either an issue with the geometry, or there's a bug I need to look into. Feel free to let me know!

**Comment by qnzhou** [comment]
Thanks @dengwirda for the explanation!  It is very helpful!
