### ISSUE TITLE
Preserving input points and edges in the resulting mesh, without resampling of the input

### ISSUE THREAD

**Issue by NikoZHAI** [dengwirda/jigsaw#20]
Hello @Darren,

I recently checked out JIGSAW and played around with some random shapes. I should first say that you did a really good work! And I hope that you can keep maintaining it!

Now I have some problems to set up JIGSAW so it will not resample the input boundaries and use the points on the boundaries in the resulting mesh. Here is the output of JIGSAW:

![steiner_points](https://user-images.githubusercontent.com/24564672/56424003-02769400-62e1-11e9-8a5f-ecd335da9f28.png)

What I would like to have is that JIGSAW preserves the input points (the small ones in black) on the boundary in the results, and no resample of the boundaries.

I roughly read the documentation in the source code but could find relevant information. Could you please kindly help?

Many thanks in advance!
Niko

**Comment by dengwirda** [comment]
Thanks @NikoZHAI, great that `JIGSAW` is working for you.

In terms of boundary (re)sampling, support for "non-refinable" edges / faces is something that's being worked on at present. The experimental `-dev` branch (should) allow a boundary mesh definition to be passed to `JIGSAW` as initial conditions, and for various nodes / edges / faces to be flagged as "fixed" so that they're not modified in either the refinement or optimisation phases.

I hope to have this work finalised over the next week or two.

One restriction though is that these initial edges / faces / etc must actually be part of the initial Delaunay triangulation -- it's not currently intended to support arbitrary collections of non-Delaunay constraints (for compatibility with `JIGSAW`'s underlying restricted Delaunay philosophy).

**Comment by NikoZHAI** [comment]
Thank you @dengwirda for replying. I will check the `dev` branch fro information!

**Comment by dengwirda** [comment]
I've now merged this into `master` (release `0.9.10`). To summarise -- "non-refinable" initial conditions can be defined by tagging any such edges / faces with negative `itag` values in the init. mesh specification.
